Modified profile page's styling
COS301-SE-2024/Culinary-Companion pull request #250
Opened 2024-07-10 15:50 UTC by Janicke01

# Modified profile page's styling

### Related issue/feature
#193 

### Description of introduced fix/feature
1. Added padding to the side of the screen
2. Made screen look fuller, added container around preferences
3. Made edit profile button more obvious

### Mentions of people responsible for reviewing the pull request
@u21463230 
@TessaEngelbrecht

2024-07-21 12:43 UTC, u22633601 requested changes
![image](https://github.com/user-attachments/assets/f49c99a1-271b-469f-b720-fbfb4dd00118)
I am getting an overflow error, will you just please look at that.

2024-07-25 06:38 UTC, u22633601 requested changes
![image](https://github.com/user-attachments/assets/baff36d0-9b27-4192-8b71-ff3532274061)

Sorry, still getting an error

2024-07-25 07:05 UTC, Janicke01 commented
Yes I know. I haven't made all the changes yet, I am still busy with it.

2024-08-11 06:11 UTC, u22633601 approved these changes

2024-08-11 06:16 UTC, merged