Improved the design of the Recipe Form
COS301-SE-2024/Culinary-Companion pull request #39
Opened 2024-06-01 14:19 UTC by Janicke01

2024-06-01 20:05 UTC, u22633601 approved these changes

2024-06-01 20:08 UTC, u22633601 requested changes
Just fix the merge conflicts with main

2024-06-02 07:04 UTC, Janicke01 reviewed
I had a look through everything and everything seems to be in order, does not like anything could cause issues on the back end side of things.

2024-06-02 07:04 UTC, Janicke01 commented on lib/screens/home_screen.dart
This was just changes to the background and text color.

2024-06-02 07:04 UTC, Janicke01 commented on lib/screens/add_recipe_screen.dart
Everything looks in order, it doesn't look if there are any merge conflicts on my side that could cause issues on the backend. Just have a look @u22633601

2024-06-02 11:50 UTC, u22633601 approved these changes

2024-06-02 11:50 UTC, merged